name: Release

on: push

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/') # 先执行 git tag -a {tag} 再执行 git push origin {tag} 以触发更新
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js  # Nodejs版本
        uses: actions/setup-node@master
        with:
          node-version: 12.13.0
      - name: Install and Build 
        run: |
          npm install
          npm run compile
          npm run compile -- --platform typora --distDir dist/typora-themes
      - name: Pack
        run: |
          cd dist/themes
          zip -r mweb-themes.zip ./
          cd ../typora-themes
          zip -r typora-themes.zip ./
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/themes/mweb-themes.zip
            dist/typora-themes/typora-themes.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}