name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js  # Nodejs版本
        uses: actions/setup-node@master
        with:
          node-version: 12.13.0
      - name: Install and Build 
        run: |
          npm install
          npm run compile
      - name: Pack
        run: zip -r mweb-themes.zip dist/themes
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: mweb-themes.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}