# 当本仓库发布新版本时，触发其他仓库自动 release
name: Trigger watched repo update 

on: push

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/') # 先执行 git tag -a {tag} 再执行 git push origin {tag} 以触发更新
    runs-on: ubuntu-latest
    steps:
      - name: Trigger release
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/imageslr/typora-theme-bear/actions/workflows/release.yaml/dispatches --data '{"ref": "master"}'
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/imageslr/typora-theme-lark/actions/workflows/release.yaml/dispatches --data '{"ref": "master"}'